# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ❤️
email: nadia.scullion@gmail.com
description: >  # this means to ignore newlines
  Nadia and Jamie request the pleasure of your company on the 9th September 2021
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nadiajamie.com/" # the base hostname & protocol for your site

static: "/static"

gift_list_url: "https://www.weddingshop.com/Buy/View/70879"


# Sass settings
sass:
    style: compressed
    sass_dir: _sass
    sourcemap: true


# Build settings
markdown: kramdown
